**IMPORTING ALL REQUIRED LIBRARY**

In [1]:
import numpy as np 
import cv2
import matplotlib.pyplot as plt

**IMPORTING OUR TRAINING AND TEST DATA**

In [2]:
X_test=np.load('/kaggle/input/training-data-distances/X_test.npy')

In [3]:
X_train=np.load('/kaggle/input/training-data-distances/X_train.npy')

In [4]:
y_test=np.load('/kaggle/input/training-data-distances/y_test.npy')

In [5]:
y_train=np.load('/kaggle/input/training-data-distances/y_train.npy')

**USING SKLEARN LIBRARY TO IMPORT RANDOMFOREST**

In [9]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score

In [10]:
rfc = RandomForestClassifier(n_estimators=50, random_state=2)

**TRAINING RANDOMFOREST LIBRARY**

In [11]:
rfc.fit(X_train,y_train)
y_pred5 = rfc.predict(X_test)
print(accuracy_score(y_test,y_pred5))
print(confusion_matrix(y_test,y_pred5))
print(precision_score(y_test,y_pred5,average='weighted'))

0.7085539147394817
[[ 650    0   29   20   76   93   61    0]
 [  11   27    9    4   11   10   13    0]
 [ 175    0  177   78   84   66   65    0]
 [  54    0   39  419   56    8   22    0]
 [ 104    0   25   20 1186   26   21    0]
 [ 281    0   37   19   97  155   77    0]
 [ 170    0   41   23  103   64  247    0]
 [   0    0    0    0    0    0    0 2225]]
0.7041721879116499


**ACHIEVED 70.41% ACCURACY IN RANDOMFOREST**

**USING ANN TO TRAIN OUR MODEL**

In [6]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from keras.callbacks import EarlyStopping

In [7]:
# number of classes
num_classes = 8
# input shape of features
input_shape = (5184,)

In [8]:
from keras.utils import to_categorical

# convert the target variables to one-hot encoded format
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

**USING 4 LAYER ANN**

In [9]:
# define the model architecture
model = Sequential([
    Dense(512, activation='relu', input_shape=input_shape),
    Dense(216, activation='relu'),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(num_classes, activation='softmax')
])
# define the optimizer with learning rate
opt = Adam(learning_rate=0.0001)



In [10]:
# compile the model with categorical cross-entropy loss and Adam optimizer
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])

In [11]:
# train the model
model.fit(X_train, y_train, batch_size=64, epochs=150, validation_data=(X_test, y_test))

Epoch 1/150
449/449 [==============================] - 6s 6ms/step - loss: 1.8066 - accuracy: 0.5605 - val_loss: 1.1474 - val_accuracy: 0.5913
Epoch 2/150
449/449 [==============================] - 2s 4ms/step - loss: 1.1446 - accuracy: 0.6013 - val_loss: 1.0867 - val_accuracy: 0.6141
Epoch 3/150
449/449 [==============================] - 3s 6ms/step - loss: 1.0901 - accuracy: 0.6104 - val_loss: 1.0526 - val_accuracy: 0.6080
Epoch 4/150
449/449 [==============================] - 2s 5ms/step - loss: 1.0525 - accuracy: 0.6163 - val_loss: 0.9421 - val_accuracy: 0.6566
Epoch 5/150
449/449 [==============================] - 2s 5ms/step - loss: 1.0253 - accuracy: 0.6267 - val_loss: 1.0446 - val_accuracy: 0.6294
Epoch 6/150
449/449 [==============================] - 2s 4ms/step - loss: 0.9947 - accuracy: 0.6329 - val_loss: 1.0230 - val_accuracy: 0.5908
Epoch 7/150
449/449 [==============================] - 2s 4ms/step - loss: 0.9755 - accuracy: 0.6410 - val_loss: 0.9618 - val_accuracy: 0.6346

**GOT MAXIMUM 70% ACCURACY USING 4 LAYER ANN**

In [ ]:
print(model)